name: build

env:
  DOCKER_REGISTRY: "franciscomoreno1"
  DOCKER_IMAGE: "hello-rust-docker"

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
      - "**/LICENSE"
      - "**/.gitignore"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Cache Cargo Dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features

      - name: Build Project
        run: cargo build --release

      - name: Run Tests
        run: cargo test

  docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: benjlevesque/short-sha@v2.2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE:${{ env.SHA }} . --no-cache

      - name: Tag Image
        run: |
          docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE:${{ env.SHA }} $DOCKER_REGISTRY/$DOCKER_IMAGE:latest

      - name: Publish Docker Image to Docker Hub
        run: |
          docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:${{ env.SHA }}
          docker push $DOCKER_REGISTRY/$DOCKER_IMAGE:latest